name: innopolis_cubit
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter_bloc: ^7.0.1
  mask_text_input_formatter: ^2.0.0
  form_field_validator: ^1.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  equatable: ^2.0.3
  hydrated_bloc: ^7.0.1
  path_provider: ^2.0.2
  fluttertoast: ^8.0.7
  freezed: ^0.14.2
  freezed_annotation: ^0.14.2
  json_annotation: 4.0.1
  get_it: ^7.1.4
  shared_preferences: ^2.0.6


dev_dependencies:
  build_runner: ^2.0.5
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true

